"""tytuł

Revision ID: 44623edc0961
Revises: 6f71149add9a
Create Date: 2021-03-11 18:05:50.586228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44623edc0961'
down_revision = '6f71149add9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genre_type', table_name='genre')
    op.drop_table('genre')
    op.create_index(op.f('ix_book_genre'), 'book', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_genre'), table_name='book')
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_genre_type', 'genre', ['type'], unique=1)
    # ### end Alembic commands ###
